# Generated by Django 4.0.6 on 2022-07-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_num', models.CharField(max_length=20)),
                ('c_name', models.CharField(max_length=50)),
                ('c_title', models.CharField(max_length=50)),
                ('c_mode', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
